### ISSUE TITLE
Issue with databroker v2 `BlueskyMongoCatalog`

### ISSUE THREAD

**Issue by mrakitin** [NSLS-II-ISS/xview#5]
When running tests against the [2022-3.1-py39-tiled](https://github.com/NSLS-II/profile-collection-ci/pull/32) environment with databroker v2+ ([PR](https://github.com/NSLS-II-ISS/profile_collection/pull/11), [logs](https://dev.azure.com/nsls2/profile_collections/_build/results?buildId=4586&view=logs&j=13ee52b2-3947-5886-3afb-8fe4d498dda0&t=991866d1-4f23-5ce7-5fb2-01a498ec459a&l=86)), I am observing the following issue:
```py
File ~/miniconda/envs/2022-2.4-py39-tiled/lib/python3.9/site-packages/xview/spectra_db/db_io.py:6, in <module>
      1 from bluesky_live.run_builder import RunBuilder
      5 from event_model import compose_run
----> 6 from databroker._drivers.mongo_normalized import BlueskyMongoCatalog
      7 from suitcase.mongo_normalized import Serializer
      8 import time as ttime

ModuleNotFoundError: No module named 'databroker._drivers'
```

@dleshchev, @danielballan, have you encountered that issue? Any suggestions on solving it?

**Comment by danielballan** [comment]
Lifted from Slack chat:

As we know, _drivers was intended to be internal, so there is no backward-compatibility plan there.

Here is a new approach: https://gist.github.com/danielballan/83e381e2ad52888ee5129d228fca7f12
Notes:
* All the Mongo stuff happens on the server side now, so the custom methods are implemented on a client object.
* I updated the `search(...)` calls to use the new query API.
* It generally recommend doing custom search and read conveniences as functions rather than methods. See https://blueskyproject.io/tiled/reference/queries.html#convenience-functions.
* The `structure_clients` injection can be done more gracefully with entrypoints, but this is the quick/explicit method.

**Comment by mrakitin** [comment]
@danielballan, thanks a lot for the suggestions and the example code! Should we now check the version of the databroker used, and apply different logic based on the version? We can do try/except of course.

@dleshchev, can we schedule 1-2 hours next week to take care of the transition? That will unblock us from switching to the tiled conda environments.

**Comment by danielballan** [comment]
Seems reasonable.

**Comment by mrakitin** [comment]
I believe it was resolved during our recent work with @dleshchev at ISS. Closing it. Please re-open if there are still concerns.
